#!/bin/bash
#SBATCH -J CNet           # Job name
#SBATCH -o log/csnet.out       # Name of stdout output file
#SBATCH -e log/csnet.err       # Name of stderr error file
#SBATCH -p gtx          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 24:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=rifatarefin19@gmail.com
#SBATCH --mail-type=all    # Send email at begin and end of job



module list
cd $WORK/semantic-code-search/src #change this line  based on where you cloned the project
pwd
date


ibrun -np 2 python3 train.py --testrun --dryrun --model selfatt