wandb_version: 1

CLI-command:
  desc: null
  value: train.py --testrun --dryrun ../saved_models ../resources/data/java/final/jsonl/train
    ../resources/data/java/final/jsonl/valid ../resources/data/java/final/jsonl/test
CUDA_VISIBLE_DEVICES:
  desc: null
  value: Not Set
_wandb:
  desc: null
  value:
    cli_version: 0.8.12
    is_jupyter_run: false
    python_version: 3.6.12
batch_size:
  desc: null
  value: 1000
code_mark_subtoken_end:
  desc: null
  value: false
code_max_num_tokens:
  desc: null
  value: 200
code_nbow_pool_mode:
  desc: null
  value: weighted_mean
code_pct_bpe:
  desc: null
  value: 0.5
code_token_embedding_size:
  desc: null
  value: 128
code_token_vocab_count_threshold:
  desc: null
  value: 10
code_token_vocab_size:
  desc: null
  value: 10000
code_use_bpe:
  desc: null
  value: true
code_use_subtokens:
  desc: null
  value: false
dropout_keep_rate:
  desc: null
  value: 0.9
fraction_using_func_name:
  desc: null
  value: 0.1
gradient_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
learning_rate_code_scale_factor:
  desc: null
  value: 1.0
learning_rate_decay:
  desc: null
  value: 0.98
learning_rate_query_scale_factor:
  desc: null
  value: 1.0
loss:
  desc: null
  value: cosine
margin:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 2
min_len_func_name_for_query:
  desc: null
  value: 12
model-class:
  desc: null
  value: neuralbowmodel
momentum:
  desc: null
  value: 0.85
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 5
query_mark_subtoken_end:
  desc: null
  value: false
query_max_num_tokens:
  desc: null
  value: 30
query_nbow_pool_mode:
  desc: null
  value: weighted_mean
query_pct_bpe:
  desc: null
  value: 0.5
query_random_token_frequency:
  desc: null
  value: 0.0
query_token_embedding_size:
  desc: null
  value: 128
query_token_vocab_count_threshold:
  desc: null
  value: 10
query_token_vocab_size:
  desc: null
  value: 10000
query_use_bpe:
  desc: null
  value: true
query_use_subtokens:
  desc: null
  value: false
run-name:
  desc: null
  value: null
save_folder:
  desc: null
  value: ../saved_models
seed:
  desc: null
  value: 0
test_folder:
  desc: null
  value: '[../resources/data/java/final/jsonl/test]'
train_folder:
  desc: null
  value: '[../resources/data/java/final/jsonl/train]'
valid_folder:
  desc: null
  value: '[../resources/data/java/final/jsonl/valid]'
